"""LLM Provider abstraction supporting Ollama (local), OpenAI, Gemini, and offline local reasoning."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod

import httpx

from app.core.config import get_settings

logger = logging.getLogger("groundwork.ai.providers")


class LLMProvider(ABC):
    """Abstract interface for LLM completion providers."""

    @abstractmethod
    def generate(self, prompt: str, system_prompt: str = "") -> str:
        """Generates a text completion given prompt and system instructions."""
        pass


class OllamaProvider(LLMProvider):
    """Local Ollama provider keeping all workspace context 100% on-device."""

    def __init__(self, base_url: str | None = None, model: str | None = None) -> None:
        settings = get_settings()
        from app.services.preferences_service import validate_url
        self.base_url = validate_url(base_url or settings.ollama_base_url, local_only=True)
        self.model = model or settings.ollama_model

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        url = f"{self.base_url}/api/chat"
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.model,
            "messages": messages,
            "stream": False,
        }

        try:
            with httpx.Client(timeout=60.0) as client:
                resp = client.post(url, json=payload)
                resp.raise_for_status()
                data = resp.json()
                return data.get("message", {}).get("content", "").strip()
        except Exception:
            logger.warning("Ollama generation failed")
            raise RuntimeError("The selected AI provider could not complete the request. Check its connection and credentials.")


class OpenAIProvider(LLMProvider):
    """OpenAI cloud provider for bounded context queries."""

    def __init__(self, api_key: str | None = None, model: str | None = None) -> None:
        settings = get_settings()
        self.api_key = api_key or settings.openai_api_key
        self.model = model or settings.openai_model

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        if not self.api_key:
            raise RuntimeError("The selected AI provider could not complete the request. Check its connection and credentials.")

        url = "https://api.openai.com/v1/chat/completions"
        headers = {"Authorization": f"Bearer {self.api_key}"}
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": 0.2,
        }

        try:
            with httpx.Client(timeout=45.0) as client:
                resp = client.post(url, headers=headers, json=payload)
                resp.raise_for_status()
                data = resp.json()
                return data["choices"][0]["message"]["content"].strip()
        except Exception:
            logger.warning("OpenAI generation failed")
            raise RuntimeError("The selected AI provider could not complete the request. Check its connection and credentials.")


class GeminiProvider(LLMProvider):
    """Google Gemini cloud provider for bounded context queries."""

    def __init__(self, api_key: str | None = None, model: str | None = None) -> None:
        settings = get_settings()
        self.api_key = api_key or settings.gemini_api_key
        self.model = model or settings.gemini_model

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        if not self.api_key:
            raise RuntimeError("The selected AI provider could not complete the request. Check its connection and credentials.")

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent"
        parts = []
        if system_prompt:
            parts.append({"text": f"SYSTEM INSTRUCTIONS:\n{system_prompt}\n\n"})
        parts.append({"text": prompt})

        payload = {
            "contents": [{"parts": parts}],
            "generationConfig": {"temperature": 0.2},
        }

        try:
            with httpx.Client(timeout=45.0) as client:
                resp = client.post(url, json=payload, headers={"x-goog-api-key": self.api_key})
                resp.raise_for_status()
                data = resp.json()
                candidates = data.get("candidates", [])
                if candidates:
                    return candidates[0]["content"]["parts"][0]["text"].strip()
                return "No response generated by Gemini."
        except Exception:
            logger.warning("Gemini generation failed")
            raise RuntimeError("The selected AI provider could not complete the request. Check its connection and credentials.")


class OfflineProvider(LLMProvider):
    """Deterministic local offline synthesizer that extracts and organizes answers from bounded evidence."""

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        lines = prompt.splitlines()
        evidence_snippets = []
        current_source = "Workspace Context"
        in_code_block = False

        for line in lines:
            if line.startswith("Project metadata from local tools:") or line.startswith("Saved investigation context ("):
                current_source = line.rstrip(":")
                continue
            if "Source [" in line or "File [" in line:
                current_source = line.strip()
                continue
            if line.strip().startswith("```"):
                in_code_block = not in_code_block
                continue
            if in_code_block and line.strip():
                evidence_snippets.append((current_source, line.strip()))

        if not evidence_snippets:
            return "No matching workspace evidence was found. Try a file name, symbol, or more specific search. Local mode shows retrieved excerpts; it does not run a language model."

        response_parts = [
            "### Local workspace excerpts",
            "",
            "These excerpts match your search. Local mode does not infer an answer or verify a diagnosis:",
            "",
        ]

        grouped: dict[str, list[str]] = {}
        for source, snippet in evidence_snippets:
            grouped.setdefault(source, [])
            if len(grouped[source]) < 3:
                grouped[source].append(snippet)
        for source, snippets in list(grouped.items())[:8]:
            response_parts.append(f"**From `{source}`**:")
            response_parts.extend(f"> {snippet}" for snippet in snippets)

        response_parts.append("")
        response_parts.append(
            "*Note: This answer was assembled locally using Groundwork's hybrid retrieval engine without sending code to the cloud.*"
        )
        return "\n".join(response_parts)


def get_llm_provider(provider_name: str | None = None) -> LLMProvider:
    """Factory function returning the active LLMProvider instance."""
    settings = get_settings()
    p_name = (provider_name or settings.ai_provider).lower()

    if p_name == "ollama":
        return OllamaProvider()
    elif p_name == "openai" and settings.openai_api_key:
        return OpenAIProvider()
    elif p_name == "gemini" and settings.gemini_api_key:
        return GeminiProvider()
    if p_name in {"openai", "gemini"}:
        raise RuntimeError("The selected provider has no API key configured")
    if p_name != "local":
        raise RuntimeError("Unknown AI provider")
    return OfflineProvider()


# Alias for test harnesses
LocalMockProvider = OfflineProvider

