"""LLM Provider abstraction supporting Ollama (local), OpenAI, Gemini, and offline local reasoning."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod

import httpx

from app.core.config import get_settings

logger = logging.getLogger("groundwork.ai.providers")


class LLMProvider(ABC):
    """Abstract interface for LLM completion providers."""

    @abstractmethod
    def generate(self, prompt: str, system_prompt: str = "") -> str:
        """Generates a text completion given prompt and system instructions."""
        pass


class OllamaProvider(LLMProvider):
    """Local Ollama provider keeping all workspace context 100% on-device."""

    def __init__(self, base_url: str | None = None, model: str | None = None) -> None:
        settings = get_settings()
        self.base_url = (base_url or settings.ollama_base_url).rstrip("/")
        self.model = model or settings.ollama_model

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        url = f"{self.base_url}/api/chat"
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.model,
            "messages": messages,
            "stream": False,
        }

        try:
            with httpx.Client(timeout=60.0) as client:
                resp = client.post(url, json=payload)
                resp.raise_for_status()
                data = resp.json()
                return data.get("message", {}).get("content", "").strip()
        except Exception as exc:
            logger.warning("Ollama generation failed (%s), using local offline fallback", exc)
            return OfflineProvider().generate(prompt, system_prompt)


class OpenAIProvider(LLMProvider):
    """OpenAI cloud provider for bounded context queries."""

    def __init__(self, api_key: str | None = None, model: str | None = None) -> None:
        settings = get_settings()
        self.api_key = api_key or settings.openai_api_key
        self.model = model or settings.openai_model

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        if not self.api_key:
            return OfflineProvider().generate(prompt, system_prompt)

        url = "https://api.openai.com/v1/chat/completions"
        headers = {"Authorization": f"Bearer {self.api_key}"}
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        payload = {
            "model": self.model,
            "messages": messages,
            "temperature": 0.2,
        }

        try:
            with httpx.Client(timeout=45.0) as client:
                resp = client.post(url, headers=headers, json=payload)
                resp.raise_for_status()
                data = resp.json()
                return data["choices"][0]["message"]["content"].strip()
        except Exception as exc:
            logger.warning("OpenAI generation failed (%s), using local fallback", exc)
            return OfflineProvider().generate(prompt, system_prompt)


class GeminiProvider(LLMProvider):
    """Google Gemini cloud provider for bounded context queries."""

    def __init__(self, api_key: str | None = None, model: str | None = None) -> None:
        settings = get_settings()
        self.api_key = api_key or settings.gemini_api_key
        self.model = model or settings.gemini_model

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        if not self.api_key:
            return OfflineProvider().generate(prompt, system_prompt)

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"
        parts = []
        if system_prompt:
            parts.append({"text": f"SYSTEM INSTRUCTIONS:\n{system_prompt}\n\n"})
        parts.append({"text": prompt})

        payload = {
            "contents": [{"parts": parts}],
            "generationConfig": {"temperature": 0.2},
        }

        try:
            with httpx.Client(timeout=45.0) as client:
                resp = client.post(url, json=payload)
                resp.raise_for_status()
                data = resp.json()
                candidates = data.get("candidates", [])
                if candidates:
                    return candidates[0]["content"]["parts"][0]["text"].strip()
                return "No response generated by Gemini."
        except Exception as exc:
            logger.warning("Gemini generation failed (%s), using local fallback", exc)
            return OfflineProvider().generate(prompt, system_prompt)


class OfflineProvider(LLMProvider):
    """Deterministic local offline synthesizer that extracts and organizes answers from bounded evidence."""

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        lines = prompt.splitlines()
        evidence_snippets = []
        current_source = "Workspace Context"
        in_code_block = False

        for line in lines:
            if "Source [" in line or "File [" in line:
                current_source = line.strip()
                continue
            if line.strip().startswith("```"):
                in_code_block = not in_code_block
                continue
            if in_code_block and line.strip():
                evidence_snippets.append((current_source, line.strip()))

        if not evidence_snippets:
            # Fallback to any non-empty lines in the prompt
            for line in lines:
                if line.strip() and not line.startswith("---") and not line.startswith("Developer Question"):
                    evidence_snippets.append(("Context", line.strip()))
                    if len(evidence_snippets) >= 5:
                        break

        response_parts = [
            "### Groundwork Local Synthesis",
            "",
            "Here is the verified evidence found in your local workspace:",
            "",
        ]

        seen_sources = set()
        for source, snippet in evidence_snippets[:8]:
            if source not in seen_sources:
                response_parts.append(f"**From `{source}`**:")
                seen_sources.add(source)
            response_parts.append(f"> {snippet}")

        response_parts.append("")
        response_parts.append(
            "*Note: This answer was assembled locally using Groundwork's hybrid retrieval engine without sending code to the cloud.*"
        )
        return "\n".join(response_parts)


def get_llm_provider(provider_name: str | None = None) -> LLMProvider:
    """Factory function returning the active LLMProvider instance."""
    settings = get_settings()
    p_name = (provider_name or settings.ai_provider).lower()

    if p_name == "ollama":
        return OllamaProvider()
    elif p_name == "openai" and settings.openai_api_key:
        return OpenAIProvider()
    elif p_name == "gemini" and settings.gemini_api_key:
        return GeminiProvider()
    return OfflineProvider()


# Alias for test harnesses
LocalMockProvider = OfflineProvider

