"""Data Transfer Objects (DTOs) and request/response validation schemas for Groundwork."""

from app.dtos.auth_dto import (
    GoogleLoginRequest,
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    TokenResponse,
)
from app.dtos.chat_dto import (
    ChatRequest,
    ChatResponse,
    CitationResponse,
    ConversationCommandRequest,
    ConversationCommandResponse,
    ConversationCreate,
    ConversationResourceCreate,
    ConversationResourceResponse,
    ConversationResponse,
    ConversationUpdate,
    MessageResponse,
)
from app.dtos.deliverable_dto import (
    AIResultResponse,
    ArtifactRenameRequest,
    ArtifactResponse,
    ArtifactVersionResponse,
    ArtifactVersionRestoreRequest,
    CommentCreateRequest,
    CommentResponse,
    DeliverableReadinessResponse,
    NativeDocumentBlocksRequest,
    NativeDocumentCreateRequest,
    NativeDocumentResponse,
    NativeDocumentSourceRequest,
    NativeDocumentUpdateRequest,
    NativeDocumentVersionResponse,
    RequirementCreateRequest,
    RequirementExtractionRequest,
    RequirementResponse,
    RequirementUpdateRequest,
    ReviewFindingDecisionRequest,
    ReviewFindingResponse,
    ReviewRunRequest,
    SuggestionCreateRequest,
    SuggestionDecisionRequest,
    SuggestionResponse,
)
from app.dtos.document_dto import (
    ArchiveFileReference,
    CollectionCreate,
    CollectionResponse,
    CollectionUpdate,
    DocumentArchiveRequest,
    DocumentMetadataUpdate,
    DocumentPageResponse,
    DocumentRenameRequest,
    DocumentResponse,
)
from app.dtos.job_dto import (
    OperationJobCreate,
    PersistedWorkflowResponse,
    PersistedWorkflowStep,
    ProcessingJobResponse,
    WorkflowEventResponse,
    WorkflowExecuteRequest,
    WorkflowPlanRequest,
    WorkflowPlanResponse,
    WorkflowStep,
)
from app.dtos.notification_dto import (
    NotificationCountResponse,
    NotificationResponse,
)
from app.dtos.tools_dto import (
    ComparisonRequest,
    ExtractionRequest,
    QuizRequest,
    SummaryRequest,
    TranslationRequest,
)
from app.dtos.user_dto import (
    AdminUserResponse,
    DashboardResponse,
    PasswordChangeRequest,
    PrivacyConfirmationRequest,
    ProfileUpdateRequest,
    SecuritySessionResponse,
    UsageDetailResponse,
    UserPreferences,
    UserResponse,
    UserStatsResponse,
    UserStatusRequest,
)
from app.dtos.workspace_dto import (
    ActivityResponse,
    ProductEventRequest,
    WorkspaceCreateRequest,
    WorkspaceMemberInviteRequest,
    WorkspaceMemberResponse,
    WorkspaceMemberRoleRequest,
    WorkspaceMemoryCreate,
    WorkspaceMemoryResponse,
    WorkspaceMemoryUpsert,
    WorkspaceResponse,
    WorkspaceSearchResult,
    WorkspaceUpdateRequest,
)

__all__ = [
    # Auth
    "RegisterRequest",
    "LoginRequest",
    "GoogleLoginRequest",
    "RefreshRequest",
    "TokenResponse",
    # User
    "UserResponse",
    "ProfileUpdateRequest",
    "UserPreferences",
    "PasswordChangeRequest",
    "UserStatsResponse",
    "DashboardResponse",
    "AdminUserResponse",
    "UserStatusRequest",
    "SecuritySessionResponse",
    "UsageDetailResponse",
    "PrivacyConfirmationRequest",
    # Workspace
    "WorkspaceResponse",
    "WorkspaceCreateRequest",
    "WorkspaceUpdateRequest",
    "WorkspaceMemberResponse",
    "WorkspaceMemberInviteRequest",
    "WorkspaceMemberRoleRequest",
    "WorkspaceMemoryCreate",
    "WorkspaceMemoryUpsert",
    "WorkspaceMemoryResponse",
    "WorkspaceSearchResult",
    "ActivityResponse",
    "ProductEventRequest",
    # Document
    "DocumentResponse",
    "DocumentRenameRequest",
    "DocumentMetadataUpdate",
    "CollectionCreate",
    "CollectionUpdate",
    "CollectionResponse",
    "ArchiveFileReference",
    "DocumentArchiveRequest",
    "DocumentPageResponse",
    # Chat
    "CitationResponse",
    "MessageResponse",
    "ConversationCreate",
    "ConversationUpdate",
    "ConversationResponse",
    "ConversationResourceCreate",
    "ConversationResourceResponse",
    "ChatRequest",
    "ChatResponse",
    "ConversationCommandRequest",
    "ConversationCommandResponse",
    # Jobs
    "ProcessingJobResponse",
    "OperationJobCreate",
    "WorkflowPlanRequest",
    "WorkflowExecuteRequest",
    "WorkflowStep",
    "WorkflowPlanResponse",
    "PersistedWorkflowStep",
    "PersistedWorkflowResponse",
    "WorkflowEventResponse",
    # Deliverables & Artifacts
    "NativeDocumentCreateRequest",
    "NativeDocumentUpdateRequest",
    "NativeDocumentBlocksRequest",
    "NativeDocumentResponse",
    "NativeDocumentVersionResponse",
    "NativeDocumentSourceRequest",
    "CommentCreateRequest",
    "CommentResponse",
    "SuggestionCreateRequest",
    "SuggestionDecisionRequest",
    "SuggestionResponse",
    "RequirementCreateRequest",
    "RequirementUpdateRequest",
    "RequirementExtractionRequest",
    "RequirementResponse",
    "ReviewRunRequest",
    "ReviewFindingDecisionRequest",
    "ReviewFindingResponse",
    "DeliverableReadinessResponse",
    "ArtifactResponse",
    "ArtifactRenameRequest",
    "ArtifactVersionResponse",
    "ArtifactVersionRestoreRequest",
    "AIResultResponse",
    # Tools
    "SummaryRequest",
    "QuizRequest",
    "ExtractionRequest",
    "TranslationRequest",
    "ComparisonRequest",
    # Notifications
    "NotificationResponse",
    "NotificationCountResponse",
]
